input {
  file {
    path => "/logs/*.json.log"
    start_position => "beginning"
    sincedb_path => "/usr/share/logstash/data/sincedb"
    codec => json
  }
}
filter {
  mutate { replace => { "environment" => "lab" } }
  date { match => ["timestamp", "ISO8601"] target => "@timestamp" }
}
output {
  elasticsearch {
    hosts => ["${ELASTICSEARCH_URL:http://elasticsearch:9200}"]
    index => "logs-app-%{+YYYY.MM.dd}"
    action => "create"
  }
  stdout { codec => dots }
}
