default_user = lab
default_pass = lab
default_user_tags.administrator = true
management.tcp.port = 15672
prometheus.tcp.port = 15692
cluster_formation.peer_discovery_backend = classic_config
cluster_formation.classic_config.nodes.1 = rabbit@rabbitmq1
cluster_formation.classic_config.nodes.2 = rabbit@rabbitmq2
cluster_formation.classic_config.nodes.3 = rabbit@rabbitmq3
cluster_partition_handling = pause_minority
queue_master_locator = min-masters
log.console.level = info
